name: "Download file if necessary"
inputs:
  url:
    description: "URL"
    required: true
outputs:
  output1:
    description: 'path to the downloaded file'
  downloaded_file:
    description: 'path to the downloaded file'
runs:
  using: "Composite"
  
  steps:
    - name: Download if necessary
      id: download_if_necessary
      shell: pwsh
      run: |
        $dir_name_downloads = "downloads"
        # ダウンロード先フォルダを作成
        New-Item -ItemType Directory -Path $dir_name_downloads -Force
        $url = "${{ inputs.url }}"
        $list_split_url = $url -split '/'
        $filename = $list_split_url[-1]
        $outputPath = $dir_name_downloads + "/" + $filename
        Write-Output "====================="
        # Write-Output $dir
        # Write-Output $url
        Write-Output $outputPath
        Write-Output "---"
        if (-Not (Test-Path -Path $outputPath)) {
            # ダウンロード
            Invoke-WebRequest -Uri $url -OutFile $outputPath
        } else {
            Write-Output "Using local copy of $outputPath"
        }
        echo "downloaded_file=$outputPath" 
        echo "downloaded_file=$outputPath" >> $env:GITHUB_OUTPUT
        echo "output1=$outputPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    - name: Check
      id: check_output
      shell: pwsh
      run: |
        echo "output1=${{ steps.download_if_necessary.outputs.output1 }}"
        echo "downloaded_file=${{ steps.download_if_necessary.outputs.downloaded_file }}"
        


